set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set-window-option -g mode-keys vi

# switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none


# panes
set -g pane-active-border-style fg=colour105

# statusbar
set -g status-style bg=colour235,fg=colour105,bold
set -g status-justify left

set -g status-left ' …. '
set -g status-right "#[fg=colour105,bold]%A, %d %b %Y %I:%M %p"

# vim esc mode delay
set -sg escape-time 1
