general {
    lock_cmd = pidof hyprlock || hyprlock 
    before_sleep_cmd = loginctl lock-session 
    after_sleep_cmd = hyprctl dispatch dpms on 
}

listener {
    event = sw_lid_close 
    on-status-changed = hyprlock
}

listener {
    timeout = 300                                
    on-timeout = loginctl lock-session           
}
